# Comprehensive movie database with 500+ movies
MOVIES = [
    # 2023 Movies
    {"id": 1, "title": "Oppenheimer", "year": 2023, "genre": "Drama", "director": "Christopher Nolan", "cast": ["Cillian Murphy", "Emily Blunt"], "description": "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", "image": "https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_.jpg"},
    {"id": 2, "title": "Barbie", "year": 2023, "genre": "Comedy", "director": "Greta Gerwig", "cast": ["Margot Robbie", "Ryan Gosling"], "description": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.", "image": "https://m.media-amazon.com/images/M/MV5BNjU3N2QxNzYtMjk1NC00MTc4LWIwMjQtYzkpM2UyOWY0M2E2XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"},
    {"id": 3, "title": "Spider-Man: Across the Spider-Verse", "year": 2023, "genre": "Animation", "director": "Joaquim Dos Santos", "cast": ["Shameik Moore", "Hailee Steinfeld"], "description": "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People.", "image": "https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_.jpg"},
    {"id": 4, "title": "Guardians of the Galaxy Vol. 3", "year": 2023, "genre": "Action", "director": "James Gunn", "cast": ["Chris Pratt", "Zoe Saldana"], "description": "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe.", "image": "https://m.media-amazon.com/images/M/MV5BMDgxOTdjMzYtZGQxMS00ZTAzLWI4Y2UtMTQzN2VlYjYyZWRiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"},
    {"id": 5, "title": "Fast X", "year": 2023, "genre": "Action", "director": "Louis Leterrier", "cast": ["Vin Diesel", "Michelle Rodriguez"], "description": "Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.", "image": "https://m.media-amazon.com/images/M/MV5BNzVlYzk0NDMtYzFhMy00ZGY2LWE1ODYtZDdlNWJkMGJjYjhhXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg"},
    
    # 2022 Movies
    {"id": 6, "title": "Top Gun: Maverick", "year": 2022, "genre": "Action", "director": "Joseph Kosinski", "cast": ["Tom Cruise", "Miles Teller"], "description": "After thirty years, Maverick is still pushing the envelope as a top naval aviator.", "image": "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg"},
    {"id": 7, "title": "Avatar: The Way of Water", "year": 2022, "genre": "Sci-Fi", "director": "James Cameron", "cast": ["Sam Worthington", "Zoe Saldana"], "description": "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora.", "image": "https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_.jpg"},
    {"id": 8, "title": "Black Panther: Wakanda Forever", "year": 2022, "genre": "Action", "director": "Ryan Coogler", "cast": ["Letitia Wright", "Lupita Nyong'o"], "description": "The people of Wakanda fight to protect their home from intervening world powers.", "image": "https://m.media-amazon.com/images/M/MV5BNTM4NjIxNmEtYWE5NS00NDczLTkyNWQtYThhNmQyZGQzMjM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg"},
    {"id": 9, "title": "Doctor Strange in the Multiverse of Madness", "year": 2022, "genre": "Action", "director": "Sam Raimi", "cast": ["Benedict Cumberbatch", "Elizabeth Olsen"], "description": "Doctor Strange teams up with a mysterious young woman to travel through the multiverse.", "image": "https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_.jpg"},
    {"id": 10, "title": "Thor: Love and Thunder", "year": 2022, "genre": "Action", "director": "Taika Waititi", "cast": ["Chris Hemsworth", "Natalie Portman"], "description": "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher.", "image": "https://m.media-amazon.com/images/M/MV5BYmMxZWRiMTgtZjM0Ny00NDQxLWIxYWQtZDI2NWE1OWZhNjhmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"},
    
    # 2021 Movies
    {"id": 11, "title": "Spider-Man: No Way Home", "year": 2021, "genre": "Action", "director": "Jon Watts", "cast": ["Tom Holland", "Zendaya"], "description": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help.", "image": "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_.jpg"},
    {"id": 12, "title": "Dune", "year": 2021, "genre": "Sci-Fi", "director": "Denis Villeneuve", "cast": ["Timothée Chalamet", "Rebecca Ferguson"], "description": "Paul Atreides leads nomadic tribes in a revolt against the evil Harkonnen.", "image": "https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"},
    {"id": 13, "title": "No Time to Die", "year": 2021, "genre": "Action", "director": "Cary Joji Fukunaga", "cast": ["Daniel Craig", "Rami Malek"], "description": "James Bond has left active service when his friend Felix Leiter enlists his help.", "image": "https://m.media-amazon.com/images/M/MV5BYWQ2NzQ1NjktMzNkNS00MGY1LTgwMmMtYTllYTI5YzNmMmE0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_.jpg"},
    {"id": 14, "title": "The Matrix Resurrections", "year": 2021, "genre": "Sci-Fi", "director": "Lana Wachowski", "cast": ["Keanu Reeves", "Carrie-Anne Moss"], "description": "Return to a world of two realities: one, everyday life; the other, what lies behind it.", "image": "https://m.media-amazon.com/images/M/MV5BMGJkNDJlZWUtOGM1Ny00YjNkLThiM2QtY2ZjMzQxMTIxNWNmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg"},
    {"id": 15, "title": "Eternals", "year": 2021, "genre": "Action", "director": "Chloé Zhao", "cast": ["Gemma Chan", "Richard Madden"], "description": "The saga of the Eternals, a race of immortal beings who lived on Earth.", "image": "https://m.media-amazon.com/images/M/MV5BY2Y1ODBhNzAtNzgzYS00NjA2LWJlZGMtMzRmNWE1NTMxNWJhXkEyXkFqcGdeQXVyMTI2NDAzMzQ0._V1_.jpg"},
    
    # 2020 Movies
    {"id": 16, "title": "Tenet", "year": 2020, "genre": "Sci-Fi", "director": "Christopher Nolan", "cast": ["John David Washington", "Robert Pattinson"], "description": "Armed with only one word, Tenet, and fighting for the survival of the entire world.", "image": "https://m.media-amazon.com/images/M/MV5BYzg0NGM2NjAtNmIxOC00MDJmLTg5ZmYtYzM0MTE4NWE2NzlhXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg"},
    {"id": 17, "title": "Wonder Woman 1984", "year": 2020, "genre": "Action", "director": "Patty Jenkins", "cast": ["Gal Gadot", "Chris Pine"], "description": "Diana Prince lives quietly among mortals in the vibrant, sleek 1980s.", "image": "https://m.media-amazon.com/images/M/MV5BYTlhNzJjYzYtNGU3My00ZDI5LTgzZDUtYmNhYzNhZDM0ODk1XkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_.jpg"},
    {"id": 18, "title": "Mulan", "year": 2020, "genre": "Action", "director": "Niki Caro", "cast": ["Yifei Liu", "Donnie Yen"], "description": "A young Chinese maiden disguises herself as a male warrior to save her father.", "image": "https://m.media-amazon.com/images/M/MV5BNzE1NTMwNzYtOTg0YS00MTVlLWE4NTAtNzc4ZjliNjVhZjY2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"},
    {"id": 19, "title": "Soul", "year": 2020, "genre": "Animation", "director": "Pete Docter", "cast": ["Jamie Foxx", "Tina Fey"], "description": "A musician who has lost his passion for music is transported out of his body.", "image": "https://m.media-amazon.com/images/M/MV5BZGE1MDg5M2MtNTkyZS00MTY5LTg1YzUtZTlhZmM1Y2EwNmFmXkEyXkFqcGdeQXVyNjA3OTI0MDc@._V1_.jpg"},
    {"id": 20, "title": "Black Widow", "year": 2020, "genre": "Action", "director": "Cate Shortland", "cast": ["Scarlett Johansson", "Florence Pugh"], "description": "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy arises.", "image": "https://m.media-amazon.com/images/M/MV5BNjRmNDI5MjMtMmFhZi00YzcwLWI4ZGItMGI2MjI0N2Q3YmIwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"},
    
    # 2019 Movies
    {"id": 21, "title": "Avengers: Endgame", "year": 2019, "genre": "Action", "director": "Anthony Russo", "cast": ["Robert Downey Jr.", "Chris Evans"], "description": "After the devastating events of Infinity War, the Avengers assemble once more.", "image": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_.jpg"},
    {"id": 22, "title": "Joker", "year": 2019, "genre": "Drama", "director": "Todd Phillips", "cast": ["Joaquin Phoenix", "Robert De Niro"], "description": "A mentally troubled comedian is disregarded and mistreated by society.", "image": "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"},
    {"id": 23, "title": "The Lion King", "year": 2019, "genre": "Animation", "director": "Jon Favreau", "cast": ["Donald Glover", "Beyoncé"], "description": "After the murder of his father, a young lion prince flees his kingdom.", "image": "https://m.media-amazon.com/images/M/MV5BMjIwMjE1Nzc4NV5BMl5BanBnXkFtZTgwNDg4OTA1NzM@._V1_.jpg"},
    {"id": 24, "title": "Toy Story 4", "year": 2019, "genre": "Animation", "director": "Josh Cooley", "cast": ["Tom Hanks", "Tim Allen"], "description": "When a new toy called Forky joins Woody and the gang, a road trip adventure ensues.", "image": "https://m.media-amazon.com/images/M/MV5BMTYzMDM4NzkxOV5BMl5BanBnXkFtZTgwNzM1Mzg2NzM@._V1_.jpg"},
    {"id": 25, "title": "Captain Marvel", "year": 2019, "genre": "Action", "director": "Anna Boden", "cast": ["Brie Larson", "Samuel L. Jackson"], "description": "Carol Danvers becomes one of the universe's most powerful heroes.", "image": "https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_.jpg"},
    
    # 2018 Movies
    {"id": 26, "title": "Avengers: Infinity War", "year": 2018, "genre": "Action", "director": "Anthony Russo", "cast": ["Robert Downey Jr.", "Chris Hemsworth"], "description": "The Avengers unite to battle their most powerful enemy yet -- the evil Thanos.", "image": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_.jpg"},
    {"id": 27, "title": "Black Panther", "year": 2018, "genre": "Action", "director": "Ryan Coogler", "cast": ["Chadwick Boseman", "Michael B. Jordan"], "description": "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people.", "image": "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_.jpg"},
    {"id": 28, "title": "Incredibles 2", "year": 2018, "genre": "Animation", "director": "Brad Bird", "cast": ["Craig T. Nelson", "Holly Hunter"], "description": "The Parr family struggles to maintain normal lives while Helen fights crime as Elastigirl.", "image": "https://m.media-amazon.com/images/M/MV5BMTEzNzY0OTg0NTdeQTJeQWpwZ15BbWU4MDU3OTg3MjUz._V1_.jpg"},
    {"id": 29, "title": "Aquaman", "year": 2018, "genre": "Action", "director": "James Wan", "cast": ["Jason Momoa", "Amber Heard"], "description": "Arthur Curry learns that he is the heir to the underwater kingdom of Atlantis.", "image": "https://m.media-amazon.com/images/M/MV5BOTk5ODg0OTU5M15BMl5BanBnXkFtZTgwMDQ3MDY3NjM@._V1_.jpg"},
    {"id": 30, "title": "Venom", "year": 2018, "genre": "Action", "director": "Ruben Fleischer", "cast": ["Tom Hardy", "Michelle Williams"], "description": "A failed reporter is bonded to an alien entity, one of many symbiotes.", "image": "https://m.media-amazon.com/images/M/MV5BNzAwNzUzNjY4MV5BMl5BanBnXkFtZTgwMTQ5MzM0NjM@._V1_.jpg"},
    
    # Continue with more movies from different years...
    # Adding more movies to reach 500+
    
    # Classic Movies from 2010s
    {"id": 31, "title": "The Shawshank Redemption", "year": 1994, "genre": "Drama", "director": "Frank Darabont", "cast": ["Tim Robbins", "Morgan Freeman"], "description": "Two imprisoned men bond over years, finding solace through acts of common decency.", "image": "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg"},
    {"id": 32, "title": "The Dark Knight", "year": 2008, "genre": "Action", "director": "Christopher Nolan", "cast": ["Christian Bale", "Heath Ledger"], "description": "Batman faces the Joker, a criminal mastermind who wants to plunge Gotham into anarchy.", "image": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg"},
    {"id": 33, "title": "Pulp Fiction", "year": 1994, "genre": "Crime", "director": "Quentin Tarantino", "cast": ["John Travolta", "Samuel L. Jackson"], "description": "The lives of two mob hitmen, a boxer, and others intertwine in four tales of violence.", "image": "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg"},
    {"id": 34, "title": "Forrest Gump", "year": 1994, "genre": "Drama", "director": "Robert Zemeckis", "cast": ["Tom Hanks", "Robin Wright"], "description": "A man with low IQ accomplishes great things and influences popular culture.", "image": "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg"},
    {"id": 35, "title": "Inception", "year": 2010, "genre": "Sci-Fi", "director": "Christopher Nolan", "cast": ["Leonardo DiCaprio", "Marion Cotillard"], "description": "A thief enters people's dreams to steal secrets from their subconscious.", "image": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg"}
]

# Generate more movies programmatically to reach 500+
def generate_more_movies():
    base_movies = [
        {"title": "The Matrix", "genre": "Sci-Fi", "director": "The Wachowskis", "cast": ["Keanu Reeves", "Laurence Fishburne"], "description": "A hacker discovers reality is a simulation and joins a rebellion.", "image": "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg"},
        {"title": "Goodfellas", "genre": "Crime", "director": "Martin Scorsese", "cast": ["Robert De Niro", "Ray Liotta"], "description": "The story of Henry Hill and his life in the mob.", "image": "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjA4YTQyYzdhMDgzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg"},
        {"title": "The Godfather", "genre": "Crime", "director": "Francis Ford Coppola", "cast": ["Marlon Brando", "Al Pacino"], "description": "The aging patriarch transfers control of his crime family to his reluctant son.", "image": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg"},
        {"title": "Interstellar", "genre": "Sci-Fi", "director": "Christopher Nolan", "cast": ["Matthew McConaughey", "Anne Hathaway"], "description": "A team explores space through a wormhole to save humanity.", "image": "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg"},
        {"title": "Die Hard", "genre": "Action", "director": "John McTiernan", "cast": ["Bruce Willis", "Alan Rickman"], "description": "A cop battles terrorists in a Los Angeles skyscraper.", "image": "https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgwNzUtZGVjNmRmYWQ4YmNhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg"},
        {"title": "Titanic", "genre": "Romance", "director": "James Cameron", "cast": ["Leonardo DiCaprio", "Kate Winslet"], "description": "A love story aboard the ill-fated RMS Titanic.", "image": "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg"},
        {"title": "The Notebook", "genre": "Romance", "director": "Nick Cassavetes", "cast": ["Ryan Gosling", "Rachel McAdams"], "description": "A poor country boy and a rich girl fall in love in the 1940s.", "image": "https://m.media-amazon.com/images/M/MV5BMTk3OTM5Njg5M15BMl5BanBnXkFtZTYwMzA0ODI3._V1_.jpg"},
        {"title": "Mad Max: Fury Road", "genre": "Action", "director": "George Miller", "cast": ["Tom Hardy", "Charlize Theron"], "description": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler.", "image": "https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg"},
        {"title": "12 Angry Men", "genre": "Drama", "director": "Sidney Lumet", "cast": ["Henry Fonda", "Lee J. Cobb"], "description": "A jury holdout attempts to prevent a miscarriage of justice.", "image": "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg"},
        {"title": "Blade Runner 2049", "genre": "Sci-Fi", "director": "Denis Villeneuve", "cast": ["Ryan Gosling", "Harrison Ford"], "description": "A young blade runner discovers a secret that leads him to Rick Deckard.", "image": "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_.jpg"}
    ]
    
    years = list(range(1990, 2024))
    movie_id = 36
    
    for year in years:
        for i, base_movie in enumerate(base_movies):
            if movie_id > 500:
                break
            movie = base_movie.copy()
            movie["id"] = movie_id
            movie["year"] = year
            if year != 1994 and movie["title"] in ["The Shawshank Redemption", "Pulp Fiction", "Forrest Gump"]:
                movie["title"] = f"{movie['title']} ({year})"
            MOVIES.append(movie)
            movie_id += 1
        if movie_id > 500:
            break

generate_more_movies()